### ISSUE TITLE
setting:  빈 화면들 및 이동 로직 추가

### ISSUE THREAD

**Issue by haeum808** [OdyOdyOdyOdy/ody-flutter#10]
##  Issue

개발하기 수월하고 머지 컨플릭트 빈도를 줄이기 위해 빈 화면들과 이동 로직을 설정하겠습니다.

##  To-do

- [x] 스플래쉬 화면
- [x] 로그인 화면
- [x] 설정 화면
- [x] 약속 목록 화면
- [x] 약속 방 개설 화면
- [x] 초대 코드 입력 화면
- [x] 약속 참여 인원들 상태 화면
- [x] 친구 위치 현황 화면
